stages:
  - test
  - build
  - docker

test:
  stage: test
  image: node:20-alpine
  script:
    - echo "Pipeline YAML válido"

build:
  stage: build
  image: node:20-alpine
  script:
    - cd backend && npm install
    - cd ../frontend && npm install && npm run build

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    # Login al registry de GitLab
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Build de imágenes
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest ./backend
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest ./frontend
    # Push al registry
    - docker push $CI_REGISTRY_IMAGE/backend:latest
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
